create table if not exists public.team_rankings (
  id bigint generated by default as identity primary key,
  room_id bigint not null unique,
  player_names text[] not null,
  player_count integer not null check (player_count between 1 and 6),
  survival_time integer not null check (survival_time >= 0),
  created_at timestamptz not null default now(),
  check (cardinality(player_names) = player_count)
);

create index if not exists team_rankings_survival_time_idx
  on public.team_rankings (survival_time desc, created_at asc);

alter table public.team_rankings enable row level security;

grant select, insert on table public.team_rankings to anon, authenticated;
grant usage, select on sequence public.team_rankings_id_seq to anon, authenticated;

drop policy if exists "team rankings are publicly readable" on public.team_rankings;
create policy "team rankings are publicly readable"
  on public.team_rankings
  for select
  to anon, authenticated
  using (true);

drop policy if exists "team rankings can be submitted" on public.team_rankings;
create policy "team rankings can be submitted"
  on public.team_rankings
  for insert
  to anon, authenticated
  with check (
    room_id > 0
    and player_count between 1 and 6
    and cardinality(player_names) = player_count
    and survival_time >= 0
  );
